### PR TITLE
fix(app service msi): Use a GET request to obtain app service MSI credentials

### PR DESCRIPTION
**Pull request by ngrewe**
We've been trying to migrate an application from the old ms-rest-azure package and noticed that we were unable to obtain MSI credentials in an Azure Functions app. That seems to have been caused by the fact that a POST request was used as opposed to a GET request as documented in the [REST protocol examples](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#rest-protocol-examples). This PR addresses the problem. 

As a bonus, there's small recurring typo fix.

### CODE REVIEW

**Comment by kpajdzik** [comment]
Thank you for your contribution! We have to adjust code to use new endpoint as localhost MSI endpoint is being deprecated and I already changed the HTTP method as a part of https://github.com/Azure/ms-rest-nodeauth/pull/45. I will merge the doc typo fixes though.

**Comment by kpajdzik** [comment]
@ngrewe Do you mind if I use this branch or should I create another PR for the typo fixes?

**Comment by ngrewe** [comment]
Correct me if I'm wrong, but #45 seems to concern MSI for Azure VMs. This PR is for using MSI in Azure App Service applications (where the endpoint is usually defined by the App Service environment using the `MSI_ENDPOINT` environment variable).
Since you mentioned it, I noticed that documentation comment for `MsiAppServiceTokenCredentials.getToken()` incorrectly talked about VMs, I've changed that.

**Comment by kpajdzik** [comment]
@ngrewe  You're totally right! I'll verify the patch and merge it at the beginning of the next week.

**Comment by Smenus** [comment]
Might have to re-bump the version number...
I wish I'd checked the issues a few hours ago, before going down a rabbit-hole trying to debug this!

**Comment by kpajdzik** [comment]
LGTM and works fine. Thanks so much for the contribution!

**Pull request merged**
